### ISSUE TITLE
Code is missing?  :-)

### ISSUE THREAD

**Issue by Tokkiu** [modriczhang/R3S#1]
Saw the repo from WSDM 2021 paper "Real-time Relevant Recommendation Suggestion".
Is this repo deprecated?
Can I get the code from any other repo?

Thank you.
:-)

**Comment by modriczhang** [comment]
Sorry for not releasing the source code in time.
I will post it in the next two or three days.

Thanks for your attention.

**Comment by modriczhang** [comment]
> Saw the repo from WSDM 2021 paper "Real-time Relevant Recommendation Suggestion".
> Is this repo deprecated?
> Can I get the code from any other repo?
> 
> Thank you.
> :-)

Sorry for not releasing the source code in time.
I will post it in the next two or three days.

Thanks for your attention.

**Comment by Tokkiu** [comment]
Thank you so much!

By the way, the taobao dataset can’t be found on net. Is it open to
developers?

Best regards
Jingqi

modriczhang ***@***.***>于2021年3月31日 周三上午10:28写道：

**Comment by Oran-Ac** [comment]
hi, any update about the source code?
